# Generated by Django 4.2 on 2025-08-07 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('security_question', models.CharField(choices=[('maiden_name', "What is your mother's maiden name?"), ('favorite_color', 'What is your favorite color?'), ('birth_city', 'What is the city where you were born?'), ('childhood_friend', 'What is the name of your childhood best friend?')], max_length=50, verbose_name='Security Question')),
                ('security_answer', models.CharField(max_length=255, verbose_name='Security Answer')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('account_executive', 'Account Executive'), ('teller', 'Teller'), ('branch_manager', 'Branch Manager')], default='customer', max_length=20, verbose_name='Role')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked')], default='active', max_length=20, verbose_name='Account Status')),
                ('id_no', models.PositiveIntegerField(unique=True, verbose_name='ID Number')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Failed Login')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='One-Time Password (OTP)')),
                ('otp_expiry', models.DateTimeField(blank=True, null=True, verbose_name='OTP Expiry')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
    ]
